name: jamb_waec_neco_prep
description: JRI PREP - JAMB, WAEC and NECO exam preparation app.
publish_to: 'none'
version: 1.2.0+3

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.2
  crypto: ^3.0.5
  url_launcher: ^6.3.1
  provider: ^6.1.2
  flutter_spinkit: ^5.2.1
  percent_indicator: ^4.2.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
